name: Styling

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  contents: read

jobs:

  php_styling:
    runs-on: ubuntu-24.04
    name: PHP
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        coverage: none
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        {
          printf 'dir='
          composer config cache-files-dir
        } >> "$GITHUB_OUTPUT"
    - name: Cache Composer
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Composer Install
      run: composer install --prefer-dist --no-progress
    - name: Check PHP Styling
      run: ./vendor/bin/phpcs -p -n --extensions=php,inc --report-width=120 --standard=ci/phpcs.xml --report=full .

  css_styling:
    runs-on: ubuntu-24.04
    name: CSS
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install npm package
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Get NPM Cache Directory
      id: npm-cache-dir
      run: |
        {
          printf 'dir='
          npm config get cache
        } >> "$GITHUB_OUTPUT"
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: NPM CI
      run: npm ci
    - name: Check CSS Styling
      run: npm run stylelint

  js_linting:
    runs-on: ubuntu-24.04
    name: JS
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install npm package
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Get NPM Cache Directory
      id: npm-cache-dir
      run: |
        {
          printf 'dir='
          npm config get cache
        } >> "$GITHUB_OUTPUT"
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: NPM CI
      run: npm ci
    - name: Check JS Linting
      run: npm run lint:js
