name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  build_apache_83_116:
    name: PHP 8.3 - Apache - MariaDB 11.6 (Rolling version)
    runs-on: ubuntu-22.04
    env:
      DOCKER_DIR: apache_83_116
      OPENEMR_DIR: /var/www/localhost/htdocs/openemr
      CHROMIUM_INSTALL: "apk update; apk add --no-cache chromium chromium-chromedriver; export PANTHER_CHROME_DRIVER_BINARY=/usr/lib/chromium/chromedriver"
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Report PHP Version
        run: php -v

      - name: Main build
        run: |
          source ci/ciLibrary.source
          composer_github_auth
          main_build

      - name: CCDA build
        run: |
          source ci/ciLibrary.source
          ccda_build

      - name: Dockers environment start
        run: |
          source ci/ciLibrary.source
          dockers_env_start

      - name: Install and configure
        run: |
          source ci/ciLibrary.source
          install_configure

      - name: Unit testing
        run: |
          source ci/ciLibrary.source
          build_test_unit
        if: ${{ success() || failure() }}

      - name: E2e testing
        run: |
          source ci/ciLibrary.source
          build_test_e2e
        if: ${{ success() || failure() }}

      - name: Api testing
        run: |
          source ci/ciLibrary.source
          build_test_api
        if: ${{ success() || failure() }}

      - name: Fixtures testing
        run: |
          source ci/ciLibrary.source
          build_test_fixtures
        if: ${{ success() || failure() }}

      - name: Services testing
        run: |
          source ci/ciLibrary.source
          build_test_services
        if: ${{ success() || failure() }}

      - name: Validators testing
        run: |
          source ci/ciLibrary.source
          build_test_validators
        if: ${{ success() || failure() }}

      - name: Controllers testing
        run: |
          source ci/ciLibrary.source
          build_test_controllers
        if: ${{ success() || failure() }}

      - name: Common testing
        run: |
          source ci/ciLibrary.source
          build_test_common
        if: ${{ success() || failure() }}

      - uses: actions/upload-artifact@v4
        with:
            name: htmlcov
            path: ./htmlcov/
