name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  build_apache_83_116:
    name: PHP 8.3 - Apache - MariaDB 11.6 (Rolling version)
    runs-on: ubuntu-22.04
    env:
      DOCKER_DIR: apache_83_116
      OPENEMR_DIR: /var/www/localhost/htdocs/openemr
      CHROMIUM_INSTALL: "apk update; apk add --no-cache chromium chromium-chromedriver; export PANTHER_CHROME_DRIVER_BINARY=/usr/lib/chromium/chromedriver"
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Report PHP Version
        run: php -v

      - name: Main build
        run: |
          . ci/ciLibrary.source
          composer_github_auth
          main_build

      - name: CCDA build
        run: |
          . ci/ciLibrary.source
          ccda_build

      - name: Dockers environment start
        run: |
          . ci/ciLibrary.source
          dockers_env_start

      - name: Install and configure
        run: |
          . ci/ciLibrary.source
          install_configure

      - name: Prepare for coverage reporting
        run: |
          . ci/ciLibrary.source
          configure_coverage

      - name: Unit testing
        run: |
          . ci/ciLibrary.source
          build_test_unit
        if: ${{ success() || failure() }}

      # - name: E2e testing
      #   run: |
      #     . ci/ciLibrary.source
      #     build_test_e2e
      #   if: ${{ success() || failure() }}

      - name: Api testing
        run: |
          . ci/ciLibrary.source
          build_test_api
        if: ${{ success() || failure() }}

      - name: Fixtures testing
        run: |
          . ci/ciLibrary.source
          build_test_fixtures
        if: ${{ success() || failure() }}

      - name: Services testing
        run: |
          . ci/ciLibrary.source
          build_test_services
        if: ${{ success() || failure() }}

      - name: Validators testing
        run: |
          . ci/ciLibrary.source
          build_test_validators
        if: ${{ success() || failure() }}

      - name: Controllers testing
        run: |
          . ci/ciLibrary.source
          build_test_controllers
        if: ${{ success() || failure() }}

      - name: Common testing
        run: |
          . ci/ciLibrary.source
          build_test_common
        if: ${{ success() || failure() }}

      - name: Combine coverage
        run: |
          . ci/ciLibrary.source
          merge_coverage
        if: ${{ success() || failure() }}

      - name: Check if coverage files exist
        if: ${{ always() }}
        id: check-files
        run: |
          echo "clover_exists=$(test -f coverage.clover.xml && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "htmlcov_exists=$(test -d ./htmlcov && echo true || echo false)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        if: ${{ always() && steps.check-files.outputs.clover_exists == 'true' }}
        with:
          name: coverage.clover.xml
          path: coverage.clover.xml

      - uses: actions/upload-artifact@v4
        if: ${{ always() && steps.check-files.outputs.htmlcov_exists == 'true' }}
        with:
          name: htmlcov
          path: ./htmlcov/

      - name: Upload coverage reports to Codecov
        if: ${{ always() && steps.check-files.outputs.clover_exists == 'true' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.clover.xml
